[package]
name = "dicom-watch"
version = "0.9.3"
edition = "2024"
build = "build.rs"

[dependencies]
iced = { version = "0.14", default-features = false, features = ["wgpu", "image", "svg", "x11", "wayland", "thread-pool"] }
notify = "8"
toml = "0.8"
serde = { version = "1", features = ["derive"] }
zip = "2"
regex = "1"
glob = "0.3"
chrono = "0.4"
rfd = "0.17.2"
rust-i18n = "4"
tray-icon = { version = "0.19", default-features = false }
image = "0.25"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["playsoundapi"] }

[target.'cfg(target_os = "linux")'.dependencies]
gtk = "0.18"

[build-dependencies]
winres = "0.1"
